// Created by iWeb 3.0.4 local-build-20121130

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,278),url:'9_Externally_Dispersed_Interferometer_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_9.png'},{rect:new IWRect(2,-2,372,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_10.png'},{rect:new IWRect(374,-2,4,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_11.png'},{rect:new IWRect(374,2,4,278),url:'9_Externally_Dispersed_Interferometer_files/stroke_12.png'},{rect:new IWRect(374,280,4,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_13.png'},{rect:new IWRect(2,280,372,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_14.png'},{rect:new IWRect(-2,280,4,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_15.png'}],new IWSize(376,282)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,252),url:'9_Externally_Dispersed_Interferometer_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_1.png'},{rect:new IWRect(2,-2,416,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_2.png'},{rect:new IWRect(418,-2,4,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_3.png'},{rect:new IWRect(418,2,4,252),url:'9_Externally_Dispersed_Interferometer_files/stroke_4.png'},{rect:new IWRect(418,254,4,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_5.png'},{rect:new IWRect(2,254,416,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_6.png'},{rect:new IWRect(-2,254,4,4),url:'9_Externally_Dispersed_Interferometer_files/stroke_7.png'}],new IWSize(420,256))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('9_Externally_Dispersed_Interferometer_files/9_Externally_Dispersed_InterferometerMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
