// Created by iWeb 3.0.4 local-build-20121130

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,292),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_9.png'},{rect:new IWRect(2,-2,390,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_10.png'},{rect:new IWRect(392,-2,5,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_11.png'},{rect:new IWRect(392,2,5,292),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_12.png'},{rect:new IWRect(392,294,5,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_13.png'},{rect:new IWRect(2,294,390,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_14.png'},{rect:new IWRect(-2,294,4,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_15.png'}],new IWSize(395,296)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,241),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_1.png'},{rect:new IWRect(2,-2,416,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_2.png'},{rect:new IWRect(418,-2,4,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_3.png'},{rect:new IWRect(418,2,4,241),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_4.png'},{rect:new IWRect(418,243,4,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_5.png'},{rect:new IWRect(2,243,416,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_6.png'},{rect:new IWRect(-2,243,4,4),url:'9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/stroke_7.png'}],new IWSize(420,245))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_Lizards_files/9_Robot_with_Inertial_Assisted_Control_by_an_Active_Tail_Inspired_by_LizardsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
