// Created by iWeb 3.0.4 local-build-20130514

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,211),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_9.png'},{rect:new IWRect(2,-2,296,4),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_10.png'},{rect:new IWRect(298,-2,5,4),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_11.png'},{rect:new IWRect(298,2,5,211),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_12.png'},{rect:new IWRect(298,213,5,5),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_13.png'},{rect:new IWRect(2,213,296,5),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_14.png'},{rect:new IWRect(-2,213,4,5),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_15.png'}],new IWSize(300,215)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,213),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_1.png'},{rect:new IWRect(2,-2,416,4),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_2.png'},{rect:new IWRect(418,-2,4,4),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_3.png'},{rect:new IWRect(418,2,4,213),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_4.png'},{rect:new IWRect(418,215,4,4),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_5.png'},{rect:new IWRect(2,215,416,4),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_6.png'},{rect:new IWRect(-2,215,4,4),url:'3_Mobile_Autonomous_Robotic_Network_files/stroke_7.png'}],new IWSize(420,217))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('3_Mobile_Autonomous_Robotic_Network_files/3_Mobile_Autonomous_Robotic_NetworkMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
