// Created by iWeb 3.0.4 local-build-20121130

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,283),url:'1_Network_based_Wireless_Rehabilitation_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_1.png'},{rect:new IWRect(2,-2,416,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_2.png'},{rect:new IWRect(418,-2,4,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_3.png'},{rect:new IWRect(418,2,4,283),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_4.png'},{rect:new IWRect(418,285,4,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_5.png'},{rect:new IWRect(2,285,416,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_6.png'},{rect:new IWRect(-2,285,4,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_7.png'}],new IWSize(420,287)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,296),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_9.png'},{rect:new IWRect(2,-2,201,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_10.png'},{rect:new IWRect(203,-2,5,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_11.png'},{rect:new IWRect(203,2,5,296),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_12.png'},{rect:new IWRect(203,298,5,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_13.png'},{rect:new IWRect(2,298,201,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_14.png'},{rect:new IWRect(-2,298,4,4),url:'1_Network_based_Wireless_Rehabilitation_files/stroke_15.png'}],new IWSize(205,300))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('1_Network_based_Wireless_Rehabilitation_files/1_Network_based_Wireless_RehabilitationMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
